---
papersize: a4
fontsize: 12pt
mainfont: "Times New Roman"
geometry: margin=2.5cm

bibliography: ./references.bib
csl: ./format/style.csl

header-includes: |
  \def\thesis{Scientia potentia est!}
---